rvm:
 - 2.3.0
 - 2.4.0
 - 2.5.0
script: 'bundle exec rspec spec'
gemfile:
  - Gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.1.gemfile
# Move to containerized travis, see http://docs.travis-ci.com/user/migrating-from-legacy
sudo: false
cache: bundler
